trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    - script: |
        echo 'Building the application...'
        # Add your build commands here
      displayName: 'Build'
      
- stage: Deploy
  displayName: 'Deployment Stage'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: 'Deployment Job'
    environment: 'Test'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo 'Deploying the application...'
              # Add your deployment commands here
            displayName: 'Deploy'
