trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    - script: |
        echo 'Building the application...'
        # Add your build commands here
      displayName: 'Build'
      
    # Publish artifacts for later stages
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'drop'
        publishLocation: 'pipeline'
  
- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
  - job: Test
    displayName: 'Test Job'
    steps:
    - download: current
      artifact: drop

    - script: |
        echo 'Running tests...'
        # Add your test commands here
      displayName: 'Run Tests'
      
- stage: DeployProd
  displayName: 'Production Deployment Stage'
  dependsOn: Test
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: 'Production Deployment Job'
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            arti
